#!/bin/bash
# Server Setup Script
# Generated on: {{.Timestamp}}
# Generated by: {{.Engineer}}

set -e

SERVER_TYPE="{{.Config.TYPE}}"
SERVER_OWNER="{{.Config.OWNER}}"
TIMEZONE="{{.Config.TIMEZONE}}"

echo "Setting up {{upper .Config.TYPE}} server..."
echo "Owner: {{.Config.OWNER}}"
echo "Timezone: {{.Config.TIMEZONE}}"

# Set timezone
timedatectl set-timezone "{{.Config.TIMEZONE}}"

{{if .HasRole "web-server"}}
# Install web server components
echo "Installing web server..."
apt-get update
apt-get install -y nginx
systemctl enable nginx
{{end}}

{{if .HasRole "database"}}
# Install database components  
echo "Installing database..."
apt-get install -y postgresql postgresql-contrib
systemctl enable postgresql
{{end}}

{{if .HasRole "monitoring-target"}}
# Install monitoring agent
echo "Installing monitoring agent..."
apt-get install -y prometheus-node-exporter
systemctl enable prometheus-node-exporter
{{end}}

# Configure services based on roles
{{range .Roles}}
echo "Configuring role: {{.}}"
{{end}}

echo "Server setup complete!"
echo "Active roles: {{join .Roles " | "}}"